version: '3.1'
services:
  stats-server:
    build: ./ewm-stats
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  ewm-service:
    build: ./ewm-main-service
    image: service_image
    container_name: service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - POSTGRES_DB=ewm-main-service
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-service
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-service
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
